version: '3.8'

services:
  db:
    image: mariadb
    environment:
      - MARIADB_USER=naba
      - MARIADB_DATABASE=naba
      - MARIADB_PASSWORD=password
      - MARIADB_ROOT_PASSWORD=password
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080